sonarqube-check:
  image:
    name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint:
      - ''
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - develop

docker-build:
  stage: build
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint:
      - ''
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s"
      "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d
      '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile
      "${CI_PROJECT_DIR}/Dockerfile" --destination
      "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
  rules:
    - if: $CI_COMMIT_BRANCH


docker-build-release:
  stage: build
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint:
      - ''
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s"
      "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d
      '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile
      "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:latest"
  only:
    - main
